import React, { useMemo } from 'react';
import { TrendingUpIcon } from '../icons/new/TrendingUpIcon';
import { formatCurrency } from '../../utils/formatters';
import { usePeopleStore } from '../../hooks/stores/usePeopleStore';
import { useFinanceStore } from '../../hooks/stores/useFinanceStore';
import { useOperationsStore } from '../../hooks/stores/useOperationsStore';
import type { Employee } from '../../types';


const ClientProfitabilityReport: React.FC = () => {
    
    const { clients, employees } = usePeopleStore();
    const { invoices } = useFinanceStore();
    const { timeLogs } = useOperationsStore();

    const profitabilityData = useMemo(() => {
        const employeeMap = new Map<string, Employee>(employees.map(e => [e.id, e]));

        return clients.map(client => {
            const revenue = invoices
                .filter(inv => inv.clientId === client.id && inv.status === 'paid')
                .reduce((sum, inv) => sum + inv.total, 0);

            const laborCost = timeLogs
                .filter(log => log.clientId === client.id)
                .reduce((total, log) => total + Object.entries(log.employeeHours).reduce((logTotal, [empId, week]) => {
                    const employee = employeeMap.get(empId);
                    if (!employee) return logTotal;
                    const reg = Object.values(week).reduce((s, d) => s + d.regular, 0);
                    const ot = Object.values(week).reduce((s, d) => s + d.overtime, 0);
                    return logTotal + (reg * employee.hourlyRate) + (ot * employee.overtimeRate);
                }, 0), 0);
            
            const profit = revenue - laborCost;
            const margin = revenue > 0 ? (profit / revenue) * 100 : 0;

            return { client, revenue, laborCost, profit, margin };
        })
        .filter(data => data.revenue > 0 || data.laborCost > 0)
        .sort((a, b) => b.profit - a.profit);
    }, [clients, employees, invoices, timeLogs]);
    
    return (
        <div className="space-y-6">
            <div>
                <h2 className="text-3xl font-bold text-gray-900 dark:text-gray-100">Client Profitability Report</h2>
                <p className="text-gray-600 dark:text-gray-400 mt-1">Analyze revenue, costs, and profit generated by each client.</p>
            </div>
            
            <div className="overflow-x-auto bg-white dark:bg-gray-800 p-0 sm:p-6 rounded-xl border border-gray-200 dark:border-gray-700 shadow-sm">
                {profitabilityData.length > 0 ? (
                    <table className="min-w-full divide-y divide-gray-200 dark:divide-gray-600">
                        <thead className="bg-gray-50 dark:bg-gray-700/50">
                            <tr>
                                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider">Client</th>
                                <th className="px-6 py-3 text-right text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider">Total Revenue (Invoiced)</th>
                                <th className="px-6 py-3 text-right text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider">Total Labor Cost</th>
                                <th className="px-6 py-3 text-right text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider">Profit</th>
                                <th className="px-6 py-3 text-right text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider">Margin</th>
                            </tr>
                        </thead>
                        <tbody className="bg-white dark:bg-gray-800 divide-y divide-gray-200 dark:divide-gray-700">
                            {profitabilityData.map(data => (
                                <tr key={data.client.id}>
                                    <td className="px-6 py-4 whitespace-nowrap font-medium text-gray-900 dark:text-gray-100">{data.client.name}</td>
                                    <td className="px-6 py-4 whitespace-nowrap text-right font-mono text-emerald-600 dark:text-emerald-400">{formatCurrency(data.revenue)}</td>
                                    <td className="px-6 py-4 whitespace-nowrap text-right font-mono text-rose-600 dark:text-rose-400">{formatCurrency(data.laborCost)}</td>
                                    <td className={`px-6 py-4 whitespace-nowrap text-right font-bold text-lg ${data.profit >= 0 ? 'text-gray-800 dark:text-gray-100' : 'text-rose-600'}`}>
                                        {formatCurrency(data.profit)}
                                    </td>
                                    <td className={`px-6 py-4 whitespace-nowrap text-right font-semibold ${data.margin >= 0 ? 'text-gray-700 dark:text-gray-200' : 'text-rose-500'}`}>
                                        {data.margin.toFixed(1)}%
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                ) : (
                    <div className="text-center py-16 px-6">
                        <TrendingUpIcon className="w-12 h-12 mx-auto text-gray-300 dark:text-gray-600" />
                        <h3 className="mt-4 text-xl font-semibold text-gray-800 dark:text-gray-100">Not enough data available</h3>
                        <p className="mt-2 text-gray-500 dark:text-gray-400">Make sure you have paid invoices and timesheets to generate this report.</p>
                    </div>
                )}
            </div>
        </div>
    );
};

export default ClientProfitabilityReport;